name: Application CD

on:
  workflow_call:

permissions:
  checks: write
  id-token: write
  contents: write
  security-events: write

jobs:
  server-deploy:
    name: Server Deployment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@main
        with:
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE }}
          aws-region: eu-west-1
          role-session-name: Server_CD_GitHub_to_AWS_via_FederatedOIDC
      
      - name: Do Nothing
        run: |
          echo "Not implemented yet"
