name: Database CD

on:
  workflow_call:

permissions:
  checks: write
  contents: read
  id-token: write

env:
  MIGRATION_LOCATION: SQL
  DOCKER_IMAGE: redgate/flyway
  SCHEMAS: public

jobs:
  migrate_db:
    name: Migrate DB
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repo
        uses: actions/checkout@main

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{secrets.AWS_ASSUME_ROLE}}
          aws-region: "eu-west-1"
          role-session-name: Database_CD_GitHub_to_AWS_via_FederatedOIDC

      - name: Get DB credentials
        uses: aws-actions/aws-secretsmanager-get-secrets@v2.0.1
        with:
          secret-ids: |
            DB_DETAILS, rds*
          parse-json-secrets: true

      - name: Fetch AWS RDS endpoint
        run: |
          echo "DB_ENDPOINT=$(aws rds describe-db-instances --db-instance-identifier spider-sweeper-db --query 'DBInstances[0].Endpoint.Address' --output text)" >> $GITHUB_ENV

      - name: Migration
        run: >-
          docker run --rm
          --volume ${{ github.workspace }}/${{ env.MIGRATION_LOCATION }}:/flyway/sql:ro
          "${{env.DB_ENDPOINT}}"
          -url="jdbc:sqlserver://${{env.DB_ENDPOINT}}:1433;authentication=sqlPassword;databaseName=SpiderSweeperDB;encrypt=false;trustServerCertificate=true"
          -user="${{ env.DB_DETAILS_USERNAME }}"
          -password="${{ env.DB_DETAILS_PASSWORD }}" 
          migrate -schemas="${{ env.SCHEMAS }}"